### ISSUE TITLE
interrupt_start / resume

### ISSUE THREAD

**Issue by drasonyx** [KoljaWindeler/ytube_music_player#126]
Sorry, I think I cannot re-open the issue, therefore I create a new one.
Please feel free to delete this one if required and re-open the original one.

Thank you

Issues I am facing after the fix:

"Not sure if it is realted to the latest fix in the beta, but I am now having issues with interrupt_start / interrupt resume when I send TTS in between.

It behaves very strangely. Sometimes it plays TTS and most times it does not, but everytime (does not matter if TTS is working or not), it will not resume to the position/track and it starts a new track on interrupt_resume."

**Comment by KoljaWindeler** [comment]
could you post your script .. what I saw is that the delay parameter is very imporant .. 
e.g. this will work find for me:

```yaml
alias: dingdong
sequence:
  - service: ytube_music_player.call_method
    data:
      command: interrupt_start
      entity_id: media_player.ytube_music_player
  - variables:
      vol: '{{ state_attr("media_player.keller_2", "volume_level") }}'
  - service: media_player.volume_set
    entity_id: media_player.keller_2
    data:
      volume_level: 1
  - service: tts.google_translate_say
    data:
      entity_id: media_player.keller_2
      message: testing, testing. this is a test message
  - delay:
      hours: 0
      minutes: 0
      seconds: 8
      milliseconds: 0
  - service: media_player.volume_set
    entity_id: media_player.keller_2
    data:
      volume_level: 0
  - service: ytube_music_player.call_method
    data:
      command: interrupt_resume
      entity_id: media_player.ytube_music_player
  - service: media_player.volume_set
    entity_id: media_player.keller_2
    data:
      volume_level: '{{vol}}'
mode: single

```

but it will fail if is set the delay e.g. for 4 sec (that delay heavily depends on the length of the message .. so i'd suggest to start with a higher number and narrow it down.

Leaving out this parameter or make it way smaller will result in a race condition. Sometimes ytube_music_player will have resumed before the TTS is actually played and therefor stopped from the TTS part .. 

.. this is a tricky command, but nice that someone is using it :D
