### ISSUE TITLE
ytube media player goes off when i run a service

### ISSUE THREAD

**Issue by IIIdefconIII** [KoljaWindeler/ytube_music_player#130]
Whenever i run the service like so:

```
service: media_player.play_media
target:
  entity_id: media_player.ytube_music_player
data:
  media_content_id: https://music.youtube.com/playlist?list=PLgQf-hEgg08ItSaLfen48CaAbZPDG5UvA
  media_content_type: youtube/video
```
The mibox turns off, do you have any idea how i could fix this? proberly cause its turning off, the playlist doenst get loaded
