### ISSUE TITLE
Continue Playback on Radio start

### ISSUE THREAD

**Issue by fr4nk2342** [KoljaWindeler/ytube_music_player#181]
## Is your feature request related to a problem? Please describe.
```yaml
service: ytube_music_player.start_radio
data: {
  entity_id: media_player.ytube_music_player
}
```
Calling this service interrupts the playback of the current track and starts a new playlist.

## Describe the solution you'd like
It would be better if the current track continues to play and only the current playlist is updated.
