### ISSUE TITLE
just "Loading" in drop down menu for select speaker

### ISSUE THREAD

**Issue by JayChun** [KoljaWindeler/ytube_music_player#192]
**Enable DEBUG Output**
Please see: https://github.com/KoljaWindeler/ytube_music_player/#debug-information

**Describe the bug**
Everything fine, there is no problem or error for playing music.
- Playing music : OK
- Select speaker via any buttons or button on ytube player : OK
- All of function of ytube : OK

Except [ Issue] below.

[ Issue ]
I'd like to add a drop down menu for selecting speaker.
But drop-down menu is just shown "Loading" as below screenshot.
![image](https://user-images.githubusercontent.com/71179304/166861920-c864b16e-5aa2-4487-b315-2abd49451b9c.png)

[ configuration.yaml ]
```
input_select:
  ytube_music_player_source:
    name: Source
    icon: mdi:music-box-multiple
    options: # don't change
    - "Playlist Radio"
    - "Playlist"

  ytube_music_player:
    name: Speakers
    icon: mdi:speaker
    options: # don't change
    - "loading"
    
  ytube_music_player_playlist:
    name: Playlist
    icon: mdi:playlist-music
    options: # don't change
    - "loading"
```

**Version**
20220415

**To Reproduce**

**Additional context**
This is speak list on HA media section, all of speakers are Google Nest.
![image](https://user-images.githubusercontent.com/71179304/166862062-83d7fdd4-cc88-498b-af40-620fe1932399.png)

And I tried to re-submit for Ytube integration, but 2 speaker group is changed 'unchecked' and error as below screenshot.
mini_bedroom/mini_album/main_sofa - speakers are google nest speaker, and group_all/group_living is speaker group Google Home made. 
![image](https://user-images.githubusercontent.com/71179304/166863261-c4fd628e-7023-4665-9be3-4b6b26d730ab.png)

Thanks
