### ISSUE TITLE
is there a way to just 'play all the songs in my library'?

### ISSUE THREAD

**Issue by jurgenweber** [KoljaWindeler/ytube_music_player#255]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can not just hit a button and play all the songs in my library

**Describe the solution you'd like**
'play all the songs in my library

**Describe alternatives you've considered**
Maybe an easy way to add all your songs in the library, into a playlist?... As a work around.

**Comment by KoljaWindeler** [comment]
hi, I've added a 'all_library_tracks' argument .. so you can start a playlist list this

```
service: media_player.play_media
data:
  media_content_id: all_library_tracks
  media_content_type: playlist
target:
  entity_id: media_player.ytube_music_player
```

that includes all you tracks in the lib

It will be part of the next release
