### ISSUE TITLE
Documentation: "Reroute debug output to error via service" does not work

### ISSUE THREAD

**Issue by ChrisHinde** [KoljaWindeler/ytube_music_player#298]
When calling the service with the YAML bellow (from the debug section of the documentation), HA responds with the error `This service requires field entity_id, which must be provided under data:`

```
service: ytube_music_player.call_method
entity_id: media_player.ytube_music_player_cf
command: debug_as_error
```

If I reformat it to this instead, I get the error `This service requires field parameters, please enter a valid value for parameters`
```
service: ytube_music_player.call_method
data:
  entity_id: media_player.ytube_music_player
  command: debug_as_error
```
  
 After some trial and error I ended up with this:
```
service: ytube_music_player.call_method
data:
  entity_id: media_player.ytube_music_player
  command: debug_as_error
  parameters: [0]
```
  
It seems to work, but I have no idea if there something specific that should be given for `parameters` (it wouldn't accept an empty list), and it doesn't match the documentation.
