### ISSUE TITLE
yTubeMediaPlayer error Please select a player before start playing, e.g. via the 'media_player.select_source' method or in the settings/config_flow

### ISSUE THREAD

**Issue by mark-baumann** [KoljaWindeler/ytube_music_player#309]
Hi Kolja,

I tried to enable the debug information, but it does not help: https://github.com/KoljaWindeler/ytube_music_player/#debug-information 

My error message is: Please select a player before start playing, e.g. via the 'media_player.select_source' method or in the settings/config_flow 

It doesnt metter what device I take as output, the error message is always the same.

I also saw the thread https://community.home-assistant.io/t/youtube-music-media-browser/226367/430?page=22 but actually I don´t know the solution.

Do you know how I can solve the issue?
I also didn´t find a config file at this custom repo.

Thanks and greetings to Hannover! 
Mark

**Comment by KoljaWindeler** [comment]
Hi Mark, while you select a speaker .. what is the debug log reporting?

**Comment by Jerry0022** [comment]
Hey Mark, I had the same issue due to my incompentence in understanding the documentation^^
After struggling it finally worked with:
`  
- service: media_player.select_source
    data:
      source: media_player.wohnzimmer_nest
      entity_id: media_player.ytube_music_player
`

**Comment by mark-baumann** [comment]
> Hey Mark, I had the same issue due to my incompentence in understanding the documentation^^ After struggling it finally worked with:
> 
> ```
>  - service: media_player.select_source
>     data:
>       source: media_player.wohnzimmer_nest
>       entity_id: media_player.ytube_music_player
> ```

Where should i type in this code? Shoud it be a seperated file?

**Comment by Jerry0022** [comment]
@mark-baumann  You can put it in an automation or script. E. g. create a new script change in the right top corner to yaml mode and overwrite everything with this code ;)

```
alias: Play Music
sequence:
  - service: media_player.select_source
    data:
      source: "{{ playbackDevice }}"
      entity_id: media_player.ytube_music_player
  - service: media_player.play_media
    data:
      media_content_id: "{{ playlistID }}"
      media_content_type: playlist
    target:
      entity_id: media_player.ytube_music_player
mode: single
icon: mdi:bullhorn
fields:
  playbackDevice:
    selector:
      entity:
        domain: media_player
    description: The media player to play it on. E.g. media_player.google_nest
    required: true
    name: Media Player Entity
  playlistID:
    selector:
      text: null
    description: >-
      Can be found in the Youtube Music Link after "list=" and before any other
      parameters separated by "&"
    required: true
    name: Playlist

```
