### ISSUE TITLE
Set repeat mode service call?

### ISSUE THREAD

**Issue by tastgr** [KoljaWindeler/ytube_music_player#329]
Would it be possible to add a "set repeat off/one/all" service call? I have an automation calling for a track to be played once, and others where repeat all would be better. Having the ability to change repeat mode in automation would be handy, as currently can only change from integration config. Cheers.

**Comment by KoljaWindeler** [comment]
Hi, ist this not working?

```
service: media_player.repeat_set
target:
  entity_id: media_player.ytube_music_player
data:
  repeat: "off"

```
