### ISSUE TITLE
Media player is stopping after one song of a playlist chosen with the new SELECT entity

### ISSUE THREAD

**Issue by wtaferner** [KoljaWindeler/ytube_music_player#339]
**Describe the bug**
It seems that there is some issue with the new playlist entity. 
After choosing a playlist, it will start to be played but is stopping after one song and you are supposed to manually call the next service on the player which is weird for a playlist.

**Version**
20240420.02 + manual fix for deprecated methods (pendling PR)

**To Reproduce**
- Choose a playlist in your Playlist Field and have your Radio Mode configured as Playlist
- Toogle your player
- Listen to the song
- After one song the media player is still on but stops playing the playlist
- Continue and get it working again by clicking NEXT (song)

**Comment by wtaferner** [comment]
It seems like the song is running again in the player (progress bar), but nothing to hear...maybe related to repeat mode?

**Comment by mang1985** [comment]
I have also reproduced this issue. VLC is working fine, but the Chromecast device is not.

**Comment by mang1985** [comment]
It appears that the issue might be related to using the new async_track_state_change_event method(#335),  which now passes an event object to the callback function instead of entity_id, old_state, and new_state parameters. This change could potentially lead to other issues. I will attempt to see if I can fix the problem based on this new method.

**Comment by wtaferner** [comment]
For mitigation with the HA onboard automations I did this:

```yaml
alias: YTubeMusic Mitigation Playlist (Player A)
description: ""
trigger:
  - platform: template
    value_template: |
      {% 
        set players = states.media_player | selectattr(
          'name', 'search', states('select.ytube_music_player_a_speaker')
        )  
      %} 
      {% set entity = players | map(attribute='entity_id') | list | first %} 
      {% if states(entity) == 'idle' %}true{% endif %}
    for:
      hours: 0
      minutes: 0
      seconds: 5
condition:
  - condition: state
    entity_id: media_player.ytube_music_player_a
    state: playing
action:
  - service: media_player.media_next_track
    metadata: {}
    data: {}
    target:
      entity_id: media_player.ytube_music_player_a
mode: single
```
