### ISSUE TITLE
Skip Track Using Remote 

### ISSUE THREAD

**Issue by pyrometheous** [KoljaWindeler/ytube_music_player#343]
I just set this up, and I love it so far, but I did run into an issue. I'm using an Nvidia Shield TV as the media player, and I've found that I can't skip ahead or to a previous track using the buttons on my remote (Harmony Hub Elite).

**Comment by pyrometheous** [comment]
I was playing around  with adb, and I noticed that if I have it enabled on the shield, and use this script, it'll cast the playlist and the remote controls it. Couldn't get it to work with SmartTube though, so that's unfortunate. But I thought I'd drop this code block for reference. Hopefully this is helpful.
```YAML
service: androidtv.adb_command
metadata: {}
data:
  command: >-
    adb shell am start -a android.intent.action.VIEW -d
    "https://www.youtube.com/watch?v=6hCqRb8Dtvo&list=RDEMb1vAi4rwXXeDlr7NZ68C_w"
target:
  device_id: **********
```
