### ISSUE TITLE
Search number or artist and then play it on my media device - question - search/action call

### ISSUE THREAD

**Issue by 1mfaasj** [KoljaWindeler/ytube_music_player#359]
Hi

can you please provide me with an example how to use service/action in HA, to search a number or artist and play it on my media device?

so I first execute this part succesfully, but what next? Do I need to do something with media browser (I saw in your docu) but it's not clear to me what you mean by this.

```
action: ytube_music_player.search
data:
  limit: 20
  query: eminem
  entity_id: media_player.ytube_music_player
```
