### ISSUE TITLE
Just got these errors

### ISSUE THREAD

**Issue by mfabiani53** [KoljaWindeler/ytube_music_player#36]
============= ytube_music_player Integration Error ================
2021-01-03 11:04:46 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2021-01-03 11:04:46 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2021-01-03 11:04:46 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] and paste the following output:

2021-01-03 11:04:46 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 133, in check_api
    self._api = ytmusicapi.YTMusic(self._header_file)
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 96, in __init__
    self.sapisid = sapisid_from_cookie(self.headers['Cookie'])
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 57, in sapisid_from_cookie
    return cookie['__Secure-3PAPISID'].value
KeyError: '__Secure-3PAPISID'

2021-01-03 11:04:46 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2021-01-03 11:04:46 ERROR (SyncWorker_2) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================

Thanks

**Comment by KoljaWindeler** [comment]
Hi, this is due to a non complete cookie, please try the cookie grabbing process again, ideally with a incognito session

**Comment by mfabiani53** [comment]
Ok, i'll try it again

**Comment by mfabiani53** [comment]
Is this entry in configuration.yaml correct?
```
  - platform: ytube_music_player
    speakers:
      - media_player.salotto_audio
      - media_player.echo_show
      - media_player.camera_ospiti
      - media_player.studio
```

**Comment by KoljaWindeler** [comment]
Nope, 
a) the speakers should be without "media_player." Only "echo_show" 
b) just so you know, if you provide this list you will limit the selection field to those players. Else all players will be shown .. but thats just an FYI

**Comment by mfabiani53** [comment]
So better to leave only ```- platform: ytube_music_player``` without any other media player?

**Comment by KoljaWindeler** [comment]
https://github.com/KoljaWindeler/ytube_music_player#configuration-options please see the 'speakers' line

**Comment by mfabiani53** [comment]
Just last question: are echo devices supported? As actually i can listen music only from my google cast devices...

**Comment by KoljaWindeler** [comment]
no worries :) 

google cast work for sure as I test on those ... alexa had some issues in the past, (read: didn't work) and I can't test .. so I'd say NO to alexa

**Comment by bobvmierlo** [comment]
I have the same error, after trying the cookie process multiple times:

See debug log output below:

```
Logger: custom_components.ytube_music_player.media_player
Source: custom_components/ytube_music_player/media_player.py:1181
Integration: YouTube Music Player (documentation, issues)
First occurred: 11:30:31 (1 occurrences)
Last logged: 11:30:31

Traceback (most recent call last): File "/config/custom_components/ytube_music_player/media_player.py", line 133, in check_api self._api = ytmusicapi.YTMusic(self._header_file) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/ytmusic.py", line 96, in __init__ self.sapisid = sapisid_from_cookie(self.headers['Cookie']) File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 57, in sapisid_from_cookie return cookie['__Secure-3PAPISID'].value KeyError: '__Secure-3PAPISID'
```

**Comment by KoljaWindeler** [comment]
yep, the cookie grabbing process is really annoying .. but there is really no way arround it ..
please make sure that you follow the guide and filter for the "browse" requrest, maybe clear the list and click on your library ... that should help. also using an incognito session helps

**Comment by mfabiani53** [comment]
I am having a lot of these errors:
```
2021-01-04 20:37:40 ERROR (SyncWorker_56) [custom_components.genius_lyrics.sensor] Missing artist and/or title
2021-01-04 20:37:40 ERROR (SyncWorker_47) [custom_components.genius_lyrics.sensor] Missing artist and/or title
2021-01-04 20:37:49 ERROR (SyncWorker_23) [custom_components.ytube_music_player.media_player] playlist to index is none!
2021-01-04 20:37:49 ERROR (SyncWorker_44) [custom_components.genius_lyrics.sensor] Missing artist and/or title
2021-01-04 20:37:49 ERROR (SyncWorker_21) [custom_components.genius_lyrics.sensor] Missing artist and/or title
2021-01-04 20:37:52 ERROR (SyncWorker_9) [custom_components.genius_lyrics.sensor] Missing artist and/or title
2021-01-04 20:37:52 ERROR (SyncWorker_60) [custom_components.genius_lyrics.sensor] Missing artist and/or title
2021-01-04 20:37:52 ERROR (SyncWorker_25) [custom_components.genius_lyrics.sensor] Missing artist and/or title
2021-01-04 20:37:52 ERROR (SyncWorker_17) [custom_components.genius_lyrics.sensor] Missing artist and/or title
```
And more the media-control card is not showing any artwork as you can see in the screenshot:
![Schermata 2021-01-04 alle 20 42 26](https://user-images.githubusercontent.com/37701688/103572764-6550fa00-4ecd-11eb-960e-fb3d5556626f.png)

**Comment by KoljaWindeler** [comment]
What error are we talking about ?
custom_components.genius_lyrics.sensor 
That one?

**Comment by KoljaWindeler** [comment]
Could you post the code for your shortcuts?

**Comment by mfabiani53** [comment]
> What error are we talking about ?
> custom_components.genius_lyrics.sensor
> That one?

Yes, that error.

This about shortcuts:
```
      - type: vertical-stack
        cards:
          - type: 'custom:mini-media-player'
            entity: media_player.ytube_music_player
            artwork: full-cover-fit
            volume_stateless: true
            hide:
              shuffle: false
              icon_state: false
              progress: false
            shortcuts:
              columns: 3
              buttons:
                - name: R&B
                  type: playlist
                  id: RDCLAK5uy_l5L-UdedbHX0pf4elWQhHVQfcFZSVXms8
                - name: Brittain Folk
                  type: playlist
                  id: RDCLAK5uy_nYYJDhiv0IfafhySgwr3-Wu4I5kzIFTV0
                - name: Chanson Francaises
                  type: playlist
                  id: PL4N9oNbOHXBUqAU7etRfVkj8vtznT5Rf2
                - name: Chill Mix
                  type: playlist
                  id: RDTMAK5uy_nefnu_8Gan5cu88bXI8YTlTZ0gpP_yfG0
                - name: Focus Mix 2
                  type: playlist
                  id: RDTMAK5uy_k3sKMy1gCfFWtnGeij2dgMRRcs2lOUxsQ
                - name: Classici Pop Rock
                  type: playlist
                  id: RDCLAK5uy_kxNTd9MzWBnemW1euSV9JwJ-Cv3XPZF9g
                - name: Philly Soul
                  type: playlist
                  id: RDCLAK5uy_mrwPvMddgVhpiTxYJ8mPNNx50V4KPUTGY
                - name: Jimi Hendrix
                  type: channel
                  id: UC5NwXf8hOgZgInaYiOCZmUg
                - name: My Super Mix
                  type: playlist
                  id: RDTMAK5uy_kset8DisdE7LSD4TNjEVvrKRTmG7a56sY
                - name: Hard Bop & Soul Jazz
                  type: playlist
                  id: RDCLAK5uy_nwcZyv_KJHkCFG-k27Xkw64ZdXMXadhx0
                - name: Frank Sinatra
                  type: channel
                  id: UC1zsfp3OD8qWQ0HfLbz2TXg
                - name: Chet Baker
                  type: channel
                  id: UCVNfRXuaWVILL9giCEg0rQg
                - name: Charlie Parker
                  type: channel
                  id: UCPFmyRluI7yvEdbHCrecUng
                - name: Miles Davis
                  type: channel
                  id: UCIev2PktTH5mI-QlGmbUkiw
                - name: Bach
                  type: channel
                  id: UCFtSXTlIMFFkyJbHO3V5b7A
```
