### ISSUE TITLE
Tracks from Playlist in pulldown menu

### ISSUE THREAD

**Issue by WHagenauw** [KoljaWindeler/ytube_music_player#85]
Is it possible to get a pulldown menu with all the tracks from the current playlist? This way it is easy to skip to another song.

**Comment by KoljaWindeler** [comment]
I guess so .. but that would require a new card for the playlist and I'm by no means a card-developer.
That said: It should be possible .. give it a try!

**Comment by KoljaWindeler** [comment]
FYI, I've implement a service call for this ticket:
```
service: ytube_music_player.call_method
data:
  entity_id: media_player.ytube_media_player
  command: goto_track
  parameter: 3 # <- e.g. 3 to go to the third track of the current playlist
```
not sure if this will ever be used but might be nice for other scenarios as well
